- name: Install nginx
  apt: name=nginx state=latest

- name: add certbot repo
  apt_repository: repo='ppa:certbot/certbot' state=present update_cache=yes
  when:
    - letsencrypt_generate == true
    - letsencrypt_domain is defined
    - letsencrypt_email is defined

- name: install certbot
  become: true
  apt: name=certbot state=latest update_cache=yes
  when:
    - letsencrypt_generate == true
    - letsencrypt_domain is defined
    - letsencrypt_email is defined

- name: start and enable service
  service: name=nginx state=started enabled=yes

- meta: flush_handlers

- name: generate certificates
  shell: certbot certonly --webroot -w /var/www/html -d {{ letsencrypt_domain }} -n --agree-tos -m {{ letsencrypt_email }}
  args:
    creates: /etc/letsencrypt/live/{{ letsencrypt_domain }}
  when:
    - letsencrypt_generate == true
    - letsencrypt_domain is defined
    - letsencrypt_email is defined

- name: remove default config
  file: name=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

- name: generate config
  template:
    src: drupal.conf
    dest: /etc/nginx/sites-enabled/drupal.conf
    owner: www-data
    group: www-data
  notify:
    - restart nginx

- name: cronjob
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: /usr/bin/certbot renew --post-hook "systemctl reload nginx"
  when:
    - letsencrypt_generate == true
    - letsencrypt_domain is defined
    - letsencrypt_email is defined
