- hosts: all
  gather_facts: true
  tasks:
  - name: update and upgrade system packages
    apt:
      upgrade: yes
      update_cache: yes

- hosts: database
  become: true
  roles:
    - mariadb
- hosts: drupal
  become: true
  roles:
    - php
    - drupal
    - nginx
