---
- hosts: all
  gather_facts: true
  tasks:
  - name: update and upgrade system packages
    apt:
      upgrade: yes
      update_cache: yes

- hosts: db-server
  roles:
    - mariadb

- hosts: web-server
  become: true
  roles:
    - php
    - drupal
    - nginx
